### ISSUE TITLE
Timed out waiting for Logon due to Notification Banner in Server

### ISSUE THREAD

**Issue by cacatic** [Blazemeter/CitrixPlugin#40]
The System Security Notice notification banner in our server prevents the logon to run automatically which causes the script to fail. This banner is shown before the Citrix User session login.

**Script Flow :**
1. In my script, MC-DownloadICA Test Fragment is used to login a Citrix user to the Citrix Storefront.
2. Then the Citrix Application Launcher opens the Citrix Receiver window.
3. On the opened Citrix Receiver window, a **System Security Notice** notification banner is shown (which is expected on our servers).
4. On this page, an ENTER key is pressed to proceed.
5. After that, the Citrix User logs in then the Authentication window of the application being tested should appear after few seconds.

![image](https://user-images.githubusercontent.com/67355836/103647549-7580dc00-4f96-11eb-949b-f4d85d37d392.png)

ERROR Details :
```
2021-01-05 12:31:43,295 [StandardJMeterEngine id:43] INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2021-01-05 12:31:43,295 [Search 1-1 id:46] INFO o.a.j.t.JMeterThread: Thread started: Search 1-1
2021-01-05 12:31:43,295 [Search 1-1 id:46] INFO c.b.j.c.s.StartApplicationSampler: Search 1-1 on sampler 00 Citrix Application Launcher ensures OCR is initialized
2021-01-05 12:31:43,295 [Search 1-1 id:46] INFO c.b.j.c.s.StartApplicationSampler: OCR initialized in 0 millis
2021-01-05 12:31:43,295 [Search 1-1 id:46] INFO o.a.j.s.FileServer: Stored: /Data/SkyPriceData.csv
2021-01-05 12:31:44,920 [ComThread for Search 1-1 id:47] INFO c.b.j.c.c.w.WinCitrixClient: Sess: des_dim=nullxnull, des_depth=nullbpp, dim=1024x768, depth=24bpp, Scr: dim=2546x1357, depth=32bpp
2021-01-05 12:32:44,414 [Search 1-1 id:46] ERROR c.b.j.c.s.CitrixBaseSampler: com.blazemeter.jmeter.citrix.sampler.SamplerRunException: Timed out waiting for Logon:Unable to handle Citrix client action. See log file for more informations.
	at com.blazemeter.jmeter.citrix.sampler.CitrixBaseSampler.handleClientAction(CitrixBaseSampler.java:166)
	at com.blazemeter.jmeter.citrix.sampler.CitrixBaseSampler.sample(CitrixBaseSampler.java:269)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:635)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.blazemeter.jmeter.citrix.client.CitrixClientException: Timed out waiting for Logon
	at com.blazemeter.jmeter.citrix.client.windows.WinCitrixClient.startSession(WinCitrixClient.java:279)
	at com.blazemeter.jmeter.citrix.client.AbstractCitrixClient.start(AbstractCitrixClient.java:375)
	at com.blazemeter.jmeter.citrix.sampler.StartApplicationSampler.doClientAction(StartApplicationSampler.java:97)
	at com.blazemeter.jmeter.citrix.sampler.CitrixBaseSampler.handleClientAction(CitrixBaseSampler.java:162)
	... 6 more

com.blazemeter.jmeter.citrix.sampler.SamplerRunException: Timed out waiting for Logon:Unable to handle Citrix client action. See log file for more informations.
	at com.blazemeter.jmeter.citrix.sampler.CitrixBaseSampler.handleClientAction(CitrixBaseSampler.java:166) ~[citrix-jmeter-0.7.0.jar:?]
	at com.blazemeter.jmeter.citrix.sampler.CitrixBaseSampler.sample(CitrixBaseSampler.java:269) [citrix-jmeter-0.7.0.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:635) [ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: com.blazemeter.jmeter.citrix.client.CitrixClientException: Timed out waiting for Logon
	at com.blazemeter.jmeter.citrix.client.windows.WinCitrixClient.startSession(WinCitrixClient.java:279) ~[citrix-jmeter-0.7.0.jar:?]
	at com.blazemeter.jmeter.citrix.client.AbstractCitrixClient.start(AbstractCitrixClient.java:375) ~[citrix-jmeter-0.7.0.jar:?]
	at com.blazemeter.jmeter.citrix.sampler.StartApplicationSampler.doClientAction(StartApplicationSampler.java:97) ~[citrix-jmeter-0.7.0.jar:?]
	at com.blazemeter.jmeter.citrix.sampler.CitrixBaseSampler.handleClientAction(CitrixBaseSampler.java:162) ~[citrix-jmeter-0.7.0.jar:?]
	... 6 more
2021-01-05 12:32:44,414 [Search 1-1 id:46] INFO o.a.j.t.JMeterThread: Stop Test Now detected by thread: Search 1-1

```

@3dgiordano provided a pre-release version of the plugin before containing a fix for this but I was hoping it can be integrated on newer releases :)

**Comment by 3dgiordano** [comment]
Hello @cacatic

It is true that I provided a version 0.6.0 without waiting for Logon so that you can automate those cases where automatic Logon does not work. Those cases that are not from XenApp but come from XenDesktop with screens of terms and conditions that was used in Desktops in XenDesktop.
The final fix was not included in the previous release 0.7.0, we have it in the roadmap for the next release.

I can provide a version without the Logon control for the current version, this way you don't need to wait for the next version to access the improvements of the current version.

In the next 24 hours I will be sending you a version 0.7.0 by private email without that Logon control so that you can migrate to the latest version of the plugin.

We will keep this issue active until its assignment for the next release where the final solution will be.

**Comment by 3dgiordano** [comment]
Hi @cacatic 

I sent you an email. 
In that email you will find a link to the latest version adapted without waiting for Logon.

**Comment by cacatic** [comment]
Thanks, @3dgiordano ! I was able to use the version you sent. I no longer encounter the issue.
_Although, I still have trouble initializing all of the users when they are more than 10, but this is a separate/different issue from the Logon event._

**Comment by 3dgiordano** [comment]
Hi @cacatic 
Excellent!
Yes, it will be for the next version to be able to choose not to wait for Logon for those cases where AutoLogon is interrupted by security changes in Windows LogonUI.

Have you reported the problem of not being able to simulate more than 10 users in another issue ticket?
Feel free to report the problem to help analyze what happens.

This ticket will remain open pending its assignment to the next version release.

**Comment by 3dgiordano** [comment]
Hi @cacatic 

You would no longer need to use the unofficial version.

The new version changes the wait for Logon to wait for an active App and a valid session.

You can download the latest version from https://github.com/Blazemeter/CitrixPlugin/releases/tag/0.7.1

**Comment by cacatic** [comment]
Used 0.7.3. Plugin with JMeter 5.4 and 5.4.1.
My script was able to proceed with the flow even with the Notification Banner on our side.

Thanks! :)
