### ISSUE TITLE
Error is displayed when trying to copy Citrix Interaction element in Jmeter tree

### ISSUE THREAD

**Issue by ndimer** [Blazemeter/CitrixPlugin#42]
Hi,

I am getting the following error when trying to copy Citrix Interaction element inside Recording Controller:
<img width="424" alt="Screen Shot 2021-02-04 at 10 25 56" src="https://user-images.githubusercontent.com/7023691/106872451-99d5f280-66d3-11eb-988e-ab7bea5c4ce7.png">

JMeter version 5.4.1
Java 8 SDK 32-bit

Please advice why could it happen?

Thanks,
Nachum

**Comment by cacatic** [comment]
I am encountering the same issue.

JMeter : 5.4.1
Citrix Plugin : 0.7.1
Java : 1.8.0_251

Here are the errors from the Log Viewer.

```
2021-02-09 11:33:22,783 [AWT-EventQueue-0 id:16] ERROR o.a.j.g.a.Copy: Clipboard node read error: com.blazemeter.jmeter.citrix.client.windows.WinCitrixClientFactory
java.io.NotSerializableException: com.blazemeter.jmeter.citrix.client.windows.WinCitrixClientFactory
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeArray(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject(Unknown Source) ~[?:1.8.0_251]
	at javax.swing.tree.DefaultMutableTreeNode.writeObject(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeArray(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.access$300(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream$PutFieldImpl.writeFields(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeFields(Unknown Source) ~[?:1.8.0_251]
	at java.util.Vector.writeObject(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.defaultWriteObject(Unknown Source) ~[?:1.8.0_251]
	at javax.swing.tree.DefaultMutableTreeNode.writeObject(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectStreamClass.invokeWriteObject(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeArray(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[?:1.8.0_251]
	at java.io.ObjectOutputStream.writeObject(Unknown Source) ~[?:1.8.0_251]
	at org.apache.jmeter.util.JMeterTreeNodeTransferable.setTransferData(JMeterTreeNodeTransferable.java:85) ~[ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.gui.action.Copy.setCopiedNodes(Copy.java:119) ~[ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.gui.action.Copy.doAction(Copy.java:66) ~[ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.4]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by 3dgiordano** [comment]
Hi @ndimer and @cacatic 
Thanks for reporting the problem, we are analyzing if it is possible to fix it in a future version.

As workaround you can use the duplicate and move the duplicated object.

**Comment by 3dgiordano** [comment]
A new version of the plugin was released today. 
Citrix Plugin v0.7.5 https://github.com/Blazemeter/CitrixPlugin/releases/tag/0.7.5
Fixed some issues around serialization.

In case the problem has not been resolved, you can reopen the ticket again reporting what was found.
